import test from'node:test';import assert from'node:assert/strict';import{createRequire}from'node:module';
const {planIntergalacticTravel:plan}=createRequire(import.meta.url)('../src/archipelagoTravel.js');
const origin={systemId:1,galaxyId:0},target={systemId:2,galaxyId:1},gates=[{id:'a',systemId:10,galaxyId:0},{id:'b',systemId:20,galaxyId:1}],connections=[{id:'ab',a:'a',b:'b'}],localLeg=(a,b)=>({ms:a.systemId===1?600000:900000,fuel:3,allowed:true});
const input={origin,target,gates,connections,localLeg,now:0,jumpFuel:()=>8};
test('cross-galaxy journey contains approach, jump and destination with a single committed ETA',()=>{const r=plan(input);assert.deepEqual(r.segments.map(s=>s.kind),['local','jump','local']);assert.equal(r.ms,55*60000);assert.equal(r.fuel,14);assert.equal(r.arrivesAt,r.ms);});
test('research reduces jump to bounded duration; slow fleet effect stays in authoritative localLeg',()=>{assert.equal(plan({...input,warp:5,hyperspace:2}).ms,45*60000);assert.equal(plan({...input,warp:1000,hyperspace:1000}).jumps,1);const slow=plan({...input,localLeg:()=>({ms:1800000,fuel:3})});assert.ok(slow.ms>plan(input).ms);});
test('same-galaxy duration delegates to existing travel calculation and aligns to the game tick',()=>{const r=plan({...input,target:{...target,galaxyId:0},now:1000});assert.equal(r.jumps,0);assert.equal(r.ms,600000);assert.equal(r.arrivesAt,900000);assert.equal(r.alignmentMs,299000);});
test('blocked or missing routes never fall back to fictional straight-line travel',()=>{assert.throws(()=>plan({...input,connections:[]}),/Keine/);assert.throws(()=>plan({...input,connections:[{...connections[0],enabled:false}]}),/Keine/);assert.throws(()=>plan({...input,localLeg:()=>({allowed:false})}),/Keine/);assert.throws(()=>plan({...input,origin:{systemId:1}}),/Zuordnung/);});
test('fastest reachable route wins and a directional route cannot be reversed',()=>{const via=[...gates,{id:'c',systemId:30,galaxyId:2}],edges=[{id:'slow',a:'a',b:'b',baseMs:7200000},{id:'ac',a:'a',b:'c'},{id:'cb',a:'c',b:'b'}];assert.equal(plan({...input,gates:via,connections:edges}).jumps,2);assert.throws(()=>plan({...input,origin:target,target:origin,connections:[{...connections[0],oneWay:true}]}),/Keine/);});
