"use strict";
const test=require("node:test"),assert=require("node:assert/strict"),fs=require("node:fs"),os=require("node:os"),path=require("node:path"),express=require("express");
const {openDb}=require("../src/db"),{ensureAdmin,ensurePlayer}=require("../src/seed"),{attachRoutes}=require("../src/routes"),settings=require("../src/settings"),nodemailer=require("nodemailer");
test("HTTP registration stays locked until an authenticated admin approves the mailed token",async t=>{
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),"nexus-auth-http-")),db=openDb(path.join(dir,"test.db"));
 ensureAdmin(db);ensurePlayer(db,"Member","secret123","Member Empire","#ff0000");settings.set(db,{betaEmail:"admin@example.org"});
 const prior={};for(const key of ["SMTP_HOST","SMTP_FROM","PUBLIC_URL"])prior[key]=process.env[key];
 Object.assign(process.env,{SMTP_HOST:"smtp.example.org",SMTP_FROM:"game@example.org",PUBLIC_URL:"https://game.example.org"});
 const original=nodemailer.createTransport,messages=[];nodemailer.createTransport=()=>({sendMail:async msg=>messages.push(msg)});
 const app=express();app.use(express.json());attachRoutes(app,db);
 const server=app.listen(0,"127.0.0.1");await new Promise(resolve=>server.once("listening",resolve));
 t.after(async()=>{await new Promise(resolve=>server.close(resolve));db.close();fs.rmSync(dir,{recursive:true,force:true});nodemailer.createTransport=original;for(const key of Object.keys(prior))if(prior[key]===undefined)delete process.env[key];else process.env[key]=prior[key];});
 const base=`http://127.0.0.1:${server.address().port}/api`;
 const post=(route,body,cookie="")=>fetch(base+route,{method:"POST",headers:{"content-type":"application/json",cookie,"x-forwarded-for":"192.0.2.55"},body:JSON.stringify(body)});
 const challenge=await fetch(base+"/auth/challenge").then(r=>r.json()),n=challenge.question.match(/\d+/g).map(Number);
 const input={username:"Applicant",email:"applicant@example.org",password:"secret123",empire:"New Empire",species:"terran",human:true,terms:true,privacy:true,age16:true,challengeId:challenge.id,answer:n[0]+n[1]};
 const response=await post("/auth/register",input);assert.equal(response.status,202);assert.equal(response.headers.get("set-cookie"),null);assert.equal(messages.length,1);
 assert.equal((await response.json()).mailSent,true);
 assert.equal((await post("/auth/login",{username:input.username,password:input.password})).status,403);
 const token=/approve\.html#([a-f0-9]+)/.exec(messages[0].text)[1];
 assert.equal((await post("/registration/approve",{token})).status,401);
 const member=await post("/auth/login",{username:"Member",password:"secret123"});
 assert.equal((await post("/registration/approve",{token},member.headers.get("set-cookie"))).status,403);
 const admin=await post("/auth/login",{username:"Admin",password:"Wurm4444"}),cookie=admin.headers.get("set-cookie");
 assert.equal((await post("/registration/review",{token},cookie)).status,200);
 assert.equal((await post("/auth/login",{username:input.username,password:input.password})).status,403);
 const approvedResponse=await post("/registration/approve",{token},cookie);
 assert.equal(approvedResponse.status,200);
 const approval=await approvedResponse.json();assert.equal(approval.playerMailSent,true);
 assert.equal(messages.length,2);assert.equal(messages[1].to,input.email);
 assert.equal(messages[1].replyTo,"mail.nexus@gmx.net");assert.match(messages[1].subject,/freigeschaltet/);
 assert.ok(!messages[1].text.includes(input.password));assert.ok(!messages[1].text.includes(token));
 assert.equal((await post(`/admin/registrations/${approval.id}/confirmation`,{})).status,401);
 assert.equal((await post(`/admin/registrations/${approval.id}/confirmation`,{},member.headers.get("set-cookie"))).status,403);
 assert.equal((await post(`/admin/registrations/${approval.id}/confirmation`,{},cookie)).status,200);
 assert.equal(messages.length,2,"Repeated confirmation does not duplicate delivery");
 assert.equal((await post("/auth/login",{username:input.username,password:input.password})).status,200);
 assert.equal((await post("/registration/approve",{token},cookie)).status,400);
 const second=await fetch(base+"/auth/challenge").then(r=>r.json()),nums=second.question.match(/\d+/g).map(Number);
 const rejected=await post("/auth/register",{...input,username:"Applicant2",email:"other@example.org",challengeId:second.id,answer:nums[0]+nums[1]});
 assert.equal(rejected.status,400);assert.match((await rejected.json()).error,/IP-Adresse/);
 // An SMTP failure must be visible without throwing away the pending account.
 db.prepare("DELETE FROM registration_requests WHERE user_id=(SELECT id FROM users WHERE username='Applicant')").run();
 nodemailer.createTransport=()=>({sendMail:async()=>{throw new Error("SMTP unavailable");}});
 const retryChallenge=await fetch(base+"/auth/challenge").then(r=>r.json()),parts=retryChallenge.question.match(/\d+/g).map(Number);
 const failure=await post("/auth/register",{...input,username:"MailFailure",email:"failure@example.org",challengeId:retryChallenge.id,answer:parts[0]+parts[1]});
 assert.equal(failure.status,202);
 const failureBody=await failure.json();assert.equal(failureBody.pending,true);assert.equal(failureBody.mailSent,false);assert.match(failureBody.message,/nicht versendet/);
 assert.equal((await post("/auth/login",{username:"MailFailure",password:input.password})).status,403);
 const pendingRequest=db.prepare("SELECT id FROM registration_requests WHERE email='failure@example.org'").get();
 nodemailer.createTransport=()=>({sendMail:async msg=>messages.push(msg)});
 assert.equal((await post(`/admin/registrations/${pendingRequest.id}/resend`,{},cookie)).status,200);
 assert.equal(db.prepare("SELECT mail_status FROM registration_requests WHERE id=?").get(pendingRequest.id).mail_status,"sent");
});
