"use strict";
const test=require("node:test"),assert=require("node:assert/strict"),fs=require("node:fs"),os=require("node:os"),path=require("node:path"),express=require("express");
const {openDb}=require("../src/db"),{ensureAdmin,ensurePlayer}=require("../src/seed"),{attachRoutes}=require("../src/routes"),settings=require("../src/settings"),nodemailer=require("nodemailer");
test("HTTP registration stays locked until an authenticated admin approves the mailed token",async t=>{
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),"nexus-auth-http-")),db=openDb(path.join(dir,"test.db"));
 ensureAdmin(db);ensurePlayer(db,"Member","secret123","Member Empire","#ff0000");settings.set(db,{betaEmail:"admin@example.org"});
 const prior={};for(const key of ["SMTP_HOST","SMTP_FROM","PUBLIC_URL"])prior[key]=process.env[key];
 Object.assign(process.env,{SMTP_HOST:"smtp.example.org",SMTP_FROM:"game@example.org",PUBLIC_URL:"https://game.example.org"});
 const original=nodemailer.createTransport,messages=[];nodemailer.createTransport=()=>({sendMail:async msg=>messages.push(msg)});
 const app=express();app.use(express.json());attachRoutes(app,db);
 const server=app.listen(0,"127.0.0.1");await new Promise(resolve=>server.once("listening",resolve));
 t.after(async()=>{await new Promise(resolve=>server.close(resolve));db.close();fs.rmSync(dir,{recursive:true,force:true});nodemailer.createTransport=original;for(const key of Object.keys(prior))if(prior[key]===undefined)delete process.env[key];else process.env[key]=prior[key];});
 const base=`http://127.0.0.1:${server.address().port}/api`;
 const post=(route,body,cookie="")=>fetch(base+route,{method:"POST",headers:{"content-type":"application/json",cookie,"x-forwarded-for":"192.0.2.55"},body:JSON.stringify(body)});
 const challenge=await fetch(base+"/auth/challenge").then(r=>r.json()),n=challenge.question.match(/\d+/g).map(Number);
 const input={username:"Applicant",email:"applicant@example.org",password:"secret123",empire:"New Empire",species:"terran",human:true,challengeId:challenge.id,answer:n[0]+n[1]};
 const response=await post("/auth/register",input);assert.equal(response.status,202);assert.equal(response.headers.get("set-cookie"),null);assert.equal(messages.length,1);
 assert.equal((await post("/auth/login",{username:input.username,password:input.password})).status,403);
 const token=/approve\.html#([a-f0-9]+)/.exec(messages[0].text)[1];
 assert.equal((await post("/registration/approve",{token})).status,401);
 const member=await post("/auth/login",{username:"Member",password:"secret123"});
 assert.equal((await post("/registration/approve",{token},member.headers.get("set-cookie"))).status,403);
 const admin=await post("/auth/login",{username:"Admin",password:"Wurm4444"}),cookie=admin.headers.get("set-cookie");
 assert.equal((await post("/registration/review",{token},cookie)).status,200);
 assert.equal((await post("/auth/login",{username:input.username,password:input.password})).status,403);
 assert.equal((await post("/registration/approve",{token},cookie)).status,200);
 assert.equal((await post("/auth/login",{username:input.username,password:input.password})).status,200);
 assert.equal((await post("/registration/approve",{token},cookie)).status,400);
 const second=await fetch(base+"/auth/challenge").then(r=>r.json()),nums=second.question.match(/\d+/g).map(Number);
 const rejected=await post("/auth/register",{...input,username:"Applicant2",email:"other@example.org",challengeId:second.id,answer:nums[0]+nums[1]});
 assert.equal(rejected.status,400);assert.match((await rejected.json()).error,/IP-Adresse/);
});
