#if UNITY_EDITOR
using System.IO;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using StellarNexus.Preview;

public static class RenderCombatPreviews {
    public static void Render() {
        string output=Path.GetFullPath(Path.Combine(Application.dataPath,"../../design/unity-previews"));Directory.CreateDirectory(output);
        foreach(bool boss in new[]{false,true}) {
            var scene=EditorSceneManager.NewScene(NewSceneSetup.EmptyScene,NewSceneMode.Single);
            var preview=CombatPreviewScene.Create(boss);
            var texture=new RenderTexture(1080,1440,24,RenderTextureFormat.ARGBHalf){antiAliasing=4};texture.Create();
            preview.WorldCamera.targetTexture=texture;preview.HudCamera.targetTexture=texture;
            preview.WorldCamera.aspect=preview.HudCamera.aspect=.75f;
            preview.SetPose(1.2f);
            preview.WorldCamera.Render();preview.HudCamera.Render();
            RenderTexture.active=texture;
            var image=new Texture2D(1080,1440,TextureFormat.RGB24,false);image.ReadPixels(new Rect(0,0,1080,1440),0,0);image.Apply();
            string name=boss?"alliance-boss":"orbit-fire";File.WriteAllBytes(Path.Combine(output,name+".png"),image.EncodeToPNG());
            RenderTexture.active=null;preview.WorldCamera.targetTexture=null;preview.HudCamera.targetTexture=null;
            Object.DestroyImmediate(image);texture.Release();Object.DestroyImmediate(texture);
            // Materials generated by this prototype are saved with the scene's asset folder.
            string assets="Assets/CombatPreview/Generated/"+name;Directory.CreateDirectory(assets);
            var materials=new System.Collections.Generic.HashSet<Material>();
            foreach(var renderer in Object.FindObjectsByType<Renderer>(FindObjectsSortMode.None))foreach(var mat in renderer.sharedMaterials)if(mat && !AssetDatabase.Contains(mat))materials.Add(mat);
            int index=0;foreach(var mat in materials){if(mat.mainTexture && !AssetDatabase.Contains(mat.mainTexture))AssetDatabase.CreateAsset(mat.mainTexture,assets+"/surface-"+index+".asset");AssetDatabase.CreateAsset(mat,assets+"/material-"+(index++)+".mat");}
            if(RenderSettings.customReflectionTexture && !AssetDatabase.Contains(RenderSettings.customReflectionTexture))AssetDatabase.CreateAsset(RenderSettings.customReflectionTexture,assets+"/reflection.asset");
            index=0;foreach(var filter in Object.FindObjectsByType<MeshFilter>(FindObjectsSortMode.None))if(filter.sharedMesh && !AssetDatabase.Contains(filter.sharedMesh))AssetDatabase.CreateAsset(filter.sharedMesh,assets+"/mesh-"+(index++)+".asset");
            EditorSceneManager.SaveScene(scene,assets+"/Preview.unity");
            EditorSceneManager.OpenScene(assets+"/Preview.unity");
            var restored=Object.FindFirstObjectByType<CombatPreviewScene>();
            if(!restored || restored.AnimatedParts==0)throw new System.Exception("Saved preview lost its animation bindings.");
            restored.SetPose(2.5f);
            restored.WorldCamera.aspect=.75f;
            if(!restored.VerifyHits())throw new System.Exception("Direct hit or miss validation failed.");
            Debug.Log("UNITY_PREVIEW_WRITTEN "+Path.Combine(output,name+".png"));
        }
        AssetDatabase.SaveAssets();
    }
}
#endif
